API Platform : Add Prestation entity.
AtoLrn/challenge-5iw3-sem1 pull request #25
Opened 2024-01-24 14:46 UTC by ChrisBradford2

### Summary
*Provide an short summary of what this pull request is for...*

### Details
*What did you do ? Exemple :*
- *login page: adding form*
- *back: fix user data not returned*
- *...*

### Important
I attest on my honor that: 
- [ ] I formatted my code
- [ ] I commented my code
- [ ] I made my code as clear as possible
- [ ] I have updated the translation file, **en** and **fr**
- [ ] I ran all the test and that they successfully pass
- [ ] I named my commit by following a good convention
- [ ] I didn't push conflicted code

### More
*More informations you want to share, like "What do you think of file X, I think there is better way ?", "Check this cool icon link"...*

2024-01-31 21:19 UTC, AtoLrn requested changes

2024-01-31 21:19 UTC, AtoLrn commented on remix/src/components/Pro/Badge.tsx
> +type StateValue = `${Validation}` | `${Kind}`;
C'est quoi ce type ?

2024-01-31 21:19 UTC, AtoLrn commented on api-platform/api/src/Entity/Prestation.php
> +          normalizationContext: ['groups' => 'prestation:read'],
Tu peux rajouter le fait d'etre log stp ?

2024-01-31 21:19 UTC, AtoLrn commented on api-platform/api/src/Entity/Prestation.php
> +      new Post(
Le faite d'etre log ici aussi

2024-01-31 21:19 UTC, AtoLrn commented on api-platform/api/src/Controller/Prestation/PrestationController.php
> +        $locationInput = $request->request->get('location');
Pourquoi il y a location ?

2024-01-31 21:19 UTC, AtoLrn commented on remix/src/routes/pro.prestations._index.tsx
> +	const response = await fetch('https://localhost/prestations/', {
Utilise la var d'env

2024-01-31 21:19 UTC, AtoLrn commented on remix/src/routes/pro.prestations._index.tsx
> +	const response = await fetch('https://localhost/prestations/', {
Et les requests devrait etre faite dans le dossier requests

2024-01-31 21:19 UTC, AtoLrn commented on remix/src/routes/pro.prestations._index.tsx
> +	const prestations = await response.json();
Faudrait verifier le type du json car la prestation est en any et on veut pas

2024-01-31 21:19 UTC, AtoLrn commented on remix/src/routes/pro.prestations._index.tsx
> +	console.log(prestations)
Retire le console log

2024-01-31 21:19 UTC, AtoLrn commented on remix/src/routes/pro.prestations.add.tsx
> +	proposedBy: z.string().min(1),
C'est une enorme faille de securite ici, le user n'est pas sense lui meme envoyer son id. Ca devrait etre le controller de api platform qui le retrouve via l'auth

2024-01-31 21:19 UTC, AtoLrn commented on remix/src/routes/pro.prestations.add.tsx
> +	location: z.string().min(1),
Y'a pas de location pour une prestation

2024-01-31 21:19 UTC, AtoLrn commented on remix/src/routes/pro.prestations.add.tsx
> +		const response = await fetch('https://localhost/prestations', {
Var d'env

2024-01-31 21:19 UTC, AtoLrn commented on remix/src/routes/pro.prestations.add.tsx
> +		const response = await fetch('https://localhost/prestations', {
+ dans le dossier request

2024-01-31 21:19 UTC, AtoLrn commented on remix/src/routes/pro.prestations.add.tsx
> +		}
Les erreurs sont en francais ou en anglais je comprends pas

2024-01-31 21:23 UTC, AtoLrn commented on api-platform/api/src/Controller/Prestation/PrestationController.php
> +        $proposedByIri = $request->request->get('proposedBy');
Recupere cet id a partir du user deja log

2024-01-31 22:03 UTC, Redeltaz commented on api-platform/api/src/Controller/Prestation/PrestationController.php
> +        $proposedByIri = $request->request->get('proposedBy');
tu peux récupérer avec le module security, tu peux regarder dans les autres controller comment je fais

2024-01-31 22:06 UTC, Redeltaz commented on api-platform/api/src/Controller/Prestation/PrestationController.php
> +        $user = $this->userRepository->findOneBy(['id' => $proposedByIri]);
Tu peux récupérer via un id directement avec $this->userRepository->find($id)

2024-01-31 22:07 UTC, Redeltaz commented on api-platform/api/src/Controller/Prestation/PrestationController.php
> +        $proposedByIri = $request->request->get('proposedBy');
+ ton nom de variable est bizarre: proposedByIri ???

2024-01-31 22:09 UTC, Redeltaz commented on api-platform/api/src/Controller/Prestation/PrestationController.php
> +        $prestation->setCreatedAt(new \DateTimeImmutable());
On ne set pas la date de la creation manuellement, depuis ton entitée rajoute un lifecycleHook, avec Prehook dans lequel tu set la date directement. Comme ça la date ne se set pas manuellement, elle se met automatiquement quand tu crée ton entitée (tu peux regarder l'entitée User c'est déjà fais)

2024-01-31 22:11 UTC, Redeltaz commented on api-platform/api/src/Controller/Prestation/PrestationController.php
Le nom du fichier est trop global, le controller permet de servir une route en particulier, la si on prévois d'ajouter d'autres controller pour Prestation les noms seront incohérent, opte plus pour un nom genre PrestationCreateController

2024-01-31 22:17 UTC, ChrisBradford2 commented on api-platform/api/src/Controller/Prestation/PrestationController.php
> +        $locationInput = $request->request->get('location');
C'était dans le schéma de la db, tu veux que je le retire ?

2024-01-31 22:20 UTC, Redeltaz commented
Tes CI ne passent pas, tu as des commits de retard par rapport à la branche master, remet toi à jour ça devrait fonctionner

2024-01-31 22:20 UTC, ChrisBradford2 commented on remix/src/components/Pro/Badge.tsx
> +type StateValue = `${Validation}` | `${Kind}`;
C'est pour dire si tu ta prestation c'est Barber, Tattoo ou Jewelery

2024-01-31 22:29 UTC, AtoLrn commented on remix/src/components/Pro/Badge.tsx
> +type StateValue = `${Validation}` | `${Kind}`;
Ça okay tu parles de l'enum mais ce pourquoi tu mets le type sous forme de string?

2024-01-31 22:29 UTC, AtoLrn commented on api-platform/api/src/Controller/Prestation/PrestationController.php
> +        $locationInput = $request->request->get('location');
On en avait parlé et on avait dit que ça ne devait pas y être

2024-01-31 22:54 UTC, ChrisBradford2 commented on remix/src/routes/pro.prestations._index.tsx
> +	const prestations = await response.json();
Avec un `'Accept': 'application/ld+json'` par exemple ?

2024-01-31 23:06 UTC, ChrisBradford2 commented on api-platform/api/src/Controller/Prestation/PrestationController.php
> +        $locationInput = $request->request->get('location');
Vu ton commentaire ci dessous, c'est retiré

2024-02-01 11:50 UTC, AtoLrn commented on remix/src/routes/pro.prestations.add.tsx
> +		console.log("Coucou" , newFormData)
Pourquoi tu recreer un formData alors que tu en as deja un ?

2024-02-01 11:50 UTC, AtoLrn commented on remix/src/routes/pro.prestations.add.tsx
> +		console.log("Coucou" , newFormData)
De plus on ne check plus le formData ?

2024-02-01 18:32 UTC, Redeltaz commented on api-platform/api/src/Controller/Prestation/PrestationUserController.php
> +        if (!$user) {
Pas besoin de checker ça, l'API renvoit direct une erreur s'il n'y a pas de token ou s'il n'est pas valide

2024-02-01 18:34 UTC, Redeltaz commented on api-platform/api/src/Controller/Prestation/PrestationUserController.php
> +        if ($this->security->isGranted('ROLE_ADMIN')) {
C'est dangereux ça, pour le retour si l'utilisateur est ADMIN, tu fais une route GetCollection qui est accessible que depuis les ADMIN, et tu laisse cette route la juste accessible aux users

2024-02-01 19:21 UTC, merged